server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genshin?useSSL=false&serverTimezone=UTC
    username: root
    password: 932811
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
